version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - mynetwork
    volumes:
      - ./influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - ./grafana_data:/var/lib/grafana

networks:
  mynetwork:
    driver: bridge
volumes:
  influxdb_data:
  grafana_data: