version: '3'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=vicguzher
      - DOCKER_INFLUXDB_INIT_PASSWORD=vicguzher
      - DOCKER_INFLUXDB_INIT_ORG=US
      - DOCKER_INFLUXDB_INIT_BUCKET=ambulancia
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=vicguzher
    networks:
      - mynetwork
    volumes:
      - ./influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    volumes:
      - ./grafana_data:/var/lib/grafana

    
networks:
  mynetwork:
    driver: bridge
volumes:
  influxdb_data:
  grafana_data: